### ISSUE TITLE
Question about what exactly this piece of code is doing

### ISSUE THREAD

**Issue by vennilaram** [brouwern/compbio2021#15]
https://github.com/brouwern/compbio2021/blob/0056a94236f0f24cc236f89ebfbae8b0d6de9d49/MSA-walkthrough-assignment-part01.Rmd#L410

Is this chunk of code just changing the class of schrooms_align to AAMultipleAlignment or is it doing something deeper?

**Comment by brouwern** [comment]
you're correct, its just changing the class (a concept we haven't gone into much) of the shrooms_align object so that it plays nice with other functions down the road.
