### ISSUE TITLE
Can someone explain to me the significance of "seqinr::alignment" here? I understand this chunk converts the msa to another type of object, but is there something we could use besides "seqinr"?

### ISSUE THREAD

**Issue by jngiroski** [brouwern/compbio2021#18]
https://github.com/brouwern/compbio2021/blob/0056a94236f0f24cc236f89ebfbae8b0d6de9d49/MSA-walkthrough-assignment-part01.Rmd#L413

**Comment by brouwern** [comment]
the main thing here is msaConvert() is just changing the format of things for us.  type = "seqinr::alignment" is just an internal setting that's getting tweaked.  If you use is() and class() on shrooms_align_seqinr and  shrooms_align you can get a sense of what is changing.  Mostly is just formatting steps to get things ready for actually interesting code.
